# Generated by Django 5.2.15 on 2026-06-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=20)),
                ('passengers', models.IntegerField()),
                ('delay', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.airport')),
            ],
        ),
    ]
